id: P000414
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1CZ1982
  title: དྲང་ངེས་ལེགས་བཤད་སྙིང་པོའི་དཀའ་འགྲེལ་
  author: ''
  volumes:
    176f18c853f34a988a59c02c5c16fd09:
      image_group_id: I1CZ2007
      title: Volume 1 of drang nges legs bshad snying po'i dka' 'grel
      volume_number: 1
      total_pages: 94
      base_file: v001.txt
